POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title":"test3",
    "author":"matti meikäläinen",
    "url":"test.url",
    "likes":5,
    "user":"6102bb6957bb9301422a257b"
}