POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: bearer 

{
    "title":"testToken",
    "author":"matti meikäläinen",
    "url":"test.url",
    "likes":0,
    "user":"6102bb6957bb9301422a257b"
}